from __future__ import annotations

import glob
import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import List

import librosa
import numpy as np

from .download import convert_to_wav_if_needed
from .utils import Segment, SongData


COG_MODEL = "r8.im/sakemin/all-in-one-music-structure-analyzer@sha256:001b4137be6ac67bdc28cb5cffacf128b874f530258d033de23121e785cb7290"


def load_index_json(json_path: str | Path) -> dict:
    with open(json_path, "r", encoding="utf-8") as f:
        return json.load(f)


def _coerce_json_payload(content: str) -> dict:
    content = content.strip()
    if (content.startswith('"') and content.endswith('"')) or (content.startswith("'") and content.endswith("'")):
        content = content[1:-1].encode("utf-8").decode("unicode_escape")
    return json.loads(content)


def analyze_audio_and_save_json(audio_path: str | Path, output_folder: str | Path, json_filename: str) -> dict:
    output_folder = Path(output_folder)
    output_folder.mkdir(parents=True, exist_ok=True)
    wav_path = convert_to_wav_if_needed(audio_path)

    cmd = ["cog", "predict", COG_MODEL, "-i", f"music_input=@{wav_path}"]
    subprocess.run(cmd, check=True, cwd=str(output_folder))

    output_jsons = glob.glob(str(output_folder / "output*.json"))
    if not output_jsons:
        raise RuntimeError("No json file generated by the analyzer.")

    output_json_path = sorted(output_jsons, key=os.path.getmtime)[-1]
    json_path = output_folder / json_filename
    shutil.copyfile(output_json_path, json_path)

    with open(json_path, "r", encoding="utf-8") as f:
        data = _coerce_json_payload(f.read())

    select_fields = ["bpm", "beats", "downbeats", "beatPositions", "segments"]
    result = {field: data.get(field) for field in select_fields}

    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2)

    return result


def _segments_from_meta(meta: dict) -> List[Segment]:
    segs: List[Segment] = []
    for i, seg in enumerate(meta.get("segments", [])):
        segs.append(
            Segment(
                start=float(seg.get("start", 0.0)),
                end=float(seg.get("end", 0.0)),
                label=str(seg.get("label", "segment")),
                idx=i,
            )
        )
    return segs


def load_song(song_dir: str | Path, sr: int = 44100) -> SongData:
    song_dir = Path(song_dir)
    paths = {
        "original": str(song_dir / "original.wav"),
        "vocals": str(song_dir / "vocals.wav"),
        "bass": str(song_dir / "bass.wav"),
        "drums": str(song_dir / "drums.wav"),
        "other": str(song_dir / "other.wav"),
    }
    for k, p in paths.items():
        if not Path(p).is_file():
            raise FileNotFoundError(f"Missing {k} at {p}")

    folder_name = song_dir.name
    json_path = song_dir / f"{folder_name}.json"
    if not json_path.is_file():
        y, _ = librosa.load(paths["original"], sr=sr, mono=True)
        tempo, beats = librosa.beat.beat_track(y=y, sr=sr)
        beat_times = librosa.frames_to_time(beats, sr=sr)
        meta = {
            "bpm": float(tempo),
            "beats": beat_times.tolist(),
            "downbeats": [],
            "beat_positions": [],
            "segments": [{"start": 0.0, "end": float(len(y) / sr), "label": "segment"}],
        }
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(meta, f, indent=2)
    meta = load_index_json(json_path)

    bpm = float(meta.get("bpm", 120.0))
    beats = np.array(meta.get("beats", []), dtype=float)
    downbeats = np.array(meta.get("downbeats", []), dtype=float)
    beat_positions = np.array(meta.get("beat_positions", []), dtype=int)
    segments = _segments_from_meta(meta)

    return SongData(
        name=folder_name,
        dirpath=str(song_dir),
        bpm=bpm,
        beats=beats,
        downbeats=downbeats,
        beat_positions=beat_positions,
        segments=segments,
        sr=sr,
        audio_paths=paths,
    )
